services:
  web-interface:
    build:
      context: web-interface/docker/development/nginx
    networks:
      - default
      - skeleton.dev
    ports:
      - "8080:80"
    volumes:
      - ./web-interface:/app

  web-interface-node:
    build:
      context: web-interface/docker/development/node
    environment:
      WDS_SOCKET_PORT: 0
      REACT_APP_AUTH_URL: http://api.localhost
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    volumes:
      - ./web-interface:/app
    tty: true

  web-interface-node-cli:
    build:
      context: web-interface/docker/development/node
    volumes:
      - ./web-interface:/app

  web-interface-angular:
    build:
      context: web-interface-angular/docker/development/nginx
    networks:
      - default
      - skeleton.dev
    ports:
      - "8081:80"
    volumes:
      - ./web-interface-angular:/app

  web-interface-angular-node:
    build:
      context: web-interface-angular/docker/development/node
    environment:
      WDS_SOCKET_PORT: 0
      REACT_APP_AUTH_URL: http://api.localhost
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    volumes:
      - ./web-interface-angular:/app
    tty: true

  web-interface-angular-node-cli:
    build:
      context: web-interface-angular/docker/development/node
    volumes:
      - ./web-interface-angular:/app

  web-interface-vuejs:
    build:
      context: web-interface-vuejs/docker/development/nginx
    networks:
      - default
      - skeleton.dev
    ports:
      - "8082:80"
    volumes:
      - ./web-interface-vuejs:/app

  web-interface-vuejs-node:
    build:
      context: web-interface-vuejs/docker/development/node
    environment:
      WDS_SOCKET_PORT: 0
      REACT_APP_AUTH_URL: http://api.localhost
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    volumes:
      - ./web-interface-vuejs:/app
    tty: true

  web-interface-vuejs-node-cli:
    build:
      context: web-interface-vuejs/docker/development/node
    volumes:
      - ./web-interface-vuejs:/app

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    networks:
      - default
      - skeleton.dev
    ports:
      - "8008:80"
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
#    environment:
#      APP_ENV: dev
#      APP_DEBUG: 1
    networks:
      - default
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
#    environment:
#      APP_ENV: dev
#      APP_DEBUG: 1
    networks:
      - default
    volumes:
      - ./api:/app

  app:
    build:
      context: backoffice/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backoffice:/app
    networks:
      - default
      - skeleton.dev
    ports:
      - "8009:80"
    depends_on:
      - app-php-fpm

  app-php-fpm:
    build:
      context: backoffice/docker
      dockerfile: development/php-fpm/Dockerfile
#    environment:
#      APP_ENV: dev
#      APP_DEBUG: 1
    networks:
      - default
    volumes:
      - ./backoffice:/app

  app-php-cli:
    build:
      context: backoffice/docker
      dockerfile: development/php-cli/Dockerfile
#    environment:
#      APP_ENV: dev
#      APP_DEBUG: 1
    networks:
      - default
    volumes:
      - ./backoffice:/app

  api-mysql:
    image: mysql:9.3
    environment:
      MYSQL_USER: app
      MYSQL_DATABASE: app
      MYSQL_PASSWORD_FILE: /run/secrets/api_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/api_db_password
    ports:
      - "13306:3306"
    networks:
      - default
    secrets:
      - api_db_password
    volumes:
      - api-mysql:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

secrets:
  api_db_password:
    file: ./docker/development/secrets/api_db_password
  api_mailer_password:
    file: ./docker/development/secrets/api_mailer_password
  sentry_dsn:
    file: ./docker/development/secrets/sentry_dsn
  jwt_encryption_key:
    file: ./docker/development/secrets/jwt_encryption_key
  jwt_public_key:
    file: ./docker/development/secrets/jwt_public_key
  jwt_private_key:
    file: ./docker/development/secrets/jwt_private_key
  backup_aws_secret_access_key:
    file: ./docker/development/secrets/backup_aws_secret_access_key

volumes:
  api-mysql:
  api-mysql-backup:
  backup-storage:

networks:
  skeleton.dev:
    name: skeleton.dev
