#controllers:
#    resource:
#        path: ../src/Http/Action/
#        namespace: App\Http\Action
#    type: attribute

controllers:
  resource: ../src/Controller/
  type: attribute

#app_index:
#    path: /
#    controller: App\Controller\HelloController::index